/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.js";
import SchemaTypes from "../../schema_types.js";
import SlackTypes from "../schema_types.js";
export default DefineFunction({
    callback_id: "slack#/functions/send_ephemeral_message",
    source_file: "",
    title: "Send an Ephemeral message",
    description: "Ephemeral messages are only visible to the assigned user in a channel or DM. Message delivery is not guaranteed - the user must be currently active in Slack. These messages are useful as confirmations after a user has clicked a button or submitted a form.",
    input_parameters: {
        required: ["user_id", "channel_id", "message"],
        properties: {
            user_id: {
                type: SlackTypes.user_id,
                description: "Send this message to this person",
            },
            channel_id: {
                type: SlackTypes.channel_id,
                description: "Send this message in this channel",
            },
            message: {
                type: SlackTypes.blocks,
                description: "Message text",
            },
            thread_ts: {
                type: SchemaTypes.string,
                description: "Another Message's ts value to make this message a reply",
            },
        },
    },
    output_parameters: {
        required: ["ts"],
        properties: {
            ts: {
                type: SchemaTypes.string,
                description: "Timestamp of the message that was sent",
            },
        },
    },
});
