#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

# Writes the Function files based on a functions.json file existing alongside this script
deno run --quiet --allow-read --allow-write ./src/write_function_files.ts

# Writes the Function TEST files based on a functions.json file existing alongside this script
deno run --quiet --allow-read --allow-write ./src/write_missing_function_tests.ts

# Remove function files not mentionned in the functions.json file
deno run --quiet --allow-read --allow-write ./src/rm_outdated_function_files.ts

echo "Formatting Slack function files..."
deno fmt --quiet ../*.ts
echo "Linting Slack function files..."
deno lint --quiet ../*.ts
