/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.js";
import SlackTypes from "../schema_types.js";

export default DefineFunction(
  {
    callback_id: "slack#/functions/invite_user_to_channel",
    source_file: "",
    title: "Invites a user to a channel",
    description: "Invites a user to a channel",
    input_parameters: {
      required: ["channel_id", "user_id"],
      properties: {
        channel_id: {
          type: SlackTypes.channel_id,
          description: "The ID of the channel to invite user to",
        },
        user_id: {
          type: SlackTypes.user_id,
          description: "User Id",
        },
      },
    },
    output_parameters: {
      required: ["user_id"],
      properties: {
        user_id: {
          type: SlackTypes.user_id,
          description: "Invited User",
        },
      },
    },
  },
);
