#!/bin/bash
set -e

# This test script is a bit of a placeholder until we move the repo to public GitHub
# and can setup CI that supports deno

deno lint src
# bundling will catch any compilation errors, even though we don't need the output
deno bundle src/mod.ts > /dev/null
# we want to ensure we're formatting consistently
deno fmt --check src
deno test src
