"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const mod_js_1 = require("../../../functions/mod.js");
const schema_types_js_1 = __importDefault(require("../schema_types.js"));
exports.default = (0, mod_js_1.DefineFunction)({
    callback_id: "slack#/functions/add_user_to_usergroup",
    source_file: "",
    title: "Add to user group",
    description: "Add someone to a Slack user group.",
    input_parameters: {
        required: ["usergroup_id", "user_id"],
        properties: {
            usergroup_id: {
                type: schema_types_js_1.default.usergroup_id,
                description: "User group",
            },
            user_id: {
                type: schema_types_js_1.default.user_id,
                description: "Person to add to the user group",
            },
        },
    },
    output_parameters: {
        required: ["usergroup_id"],
        properties: {
            usergroup_id: {
                type: schema_types_js_1.default.usergroup_id,
                description: "Updated usergroup",
            },
        },
    },
});
