"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const mod_js_1 = require("../../../functions/mod.js");
const schema_types_js_1 = __importDefault(require("../../schema_types.js"));
const schema_types_js_2 = __importDefault(require("../schema_types.js"));
exports.default = (0, mod_js_1.DefineFunction)({
    callback_id: "slack#/functions/create_usergroup",
    source_file: "",
    title: "Create a user group",
    description: "Create a Slack user group.",
    input_parameters: {
        required: ["usergroup_handle", "usergroup_name"],
        properties: {
            usergroup_handle: {
                type: schema_types_js_1.default.string,
                description: "User group name",
            },
            usergroup_name: {
                type: schema_types_js_1.default.string,
                description: "User group friendly name",
            },
        },
    },
    output_parameters: {
        required: ["usergroup_id"],
        properties: {
            usergroup_id: {
                type: schema_types_js_2.default.usergroup_id,
                description: "Created Usergroup",
            },
        },
    },
});
