"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const mod_js_1 = require("../../../functions/mod.js");
const schema_types_js_1 = __importDefault(require("../../schema_types.js"));
exports.default = (0, mod_js_1.DefineFunction)({
    callback_id: "slack#/functions/delay",
    source_file: "",
    title: "Delay",
    description: "Pause your workflow by adding a delay!",
    input_parameters: {
        required: ["minutes_to_delay"],
        properties: {
            minutes_to_delay: {
                type: schema_types_js_1.default.integer,
                description: "Minutes to Delay",
            },
        },
    },
    output_parameters: {
        required: [],
        properties: {},
    },
});
