"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const mod_js_1 = require("../../../functions/mod.js");
const schema_types_js_1 = __importDefault(require("../schema_types.js"));
exports.default = (0, mod_js_1.DefineFunction)({
    callback_id: "slack#/functions/invite_user_to_channel",
    source_file: "",
    title: "Invites a user to a channel",
    description: "Invites a user to a channel",
    input_parameters: {
        required: ["channel_id", "user_id"],
        properties: {
            channel_id: {
                type: schema_types_js_1.default.channel_id,
                description: "The ID of the channel to invite user to",
            },
            user_id: {
                type: schema_types_js_1.default.user_id,
                description: "User Id",
            },
        },
    },
    output_parameters: {
        required: ["user_id"],
        properties: {
            user_id: {
                type: schema_types_js_1.default.user_id,
                description: "Invited User",
            },
        },
    },
});
