"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const add_pin_js_1 = __importDefault(require("./add_pin.js"));
const add_user_to_usergroup_js_1 = __importDefault(require("./add_user_to_usergroup.js"));
const archive_channel_js_1 = __importDefault(require("./archive_channel.js"));
const create_channel_js_1 = __importDefault(require("./create_channel.js"));
const create_usergroup_js_1 = __importDefault(require("./create_usergroup.js"));
const delay_js_1 = __importDefault(require("./delay.js"));
const invite_user_to_channel_js_1 = __importDefault(require("./invite_user_to_channel.js"));
const remove_user_from_usergroup_js_1 = __importDefault(require("./remove_user_from_usergroup.js"));
const rename_channel_js_1 = __importDefault(require("./rename_channel.js"));
const send_dm_js_1 = __importDefault(require("./send_dm.js"));
const send_ephemeral_message_js_1 = __importDefault(require("./send_ephemeral_message.js"));
const send_message_js_1 = __importDefault(require("./send_message.js"));
const update_channel_topic_js_1 = __importDefault(require("./update_channel_topic.js"));
const SlackFunctions = {
    AddPin: add_pin_js_1.default,
    AddUserToUsergroup: add_user_to_usergroup_js_1.default,
    ArchiveChannel: archive_channel_js_1.default,
    CreateChannel: create_channel_js_1.default,
    CreateUsergroup: create_usergroup_js_1.default,
    Delay: delay_js_1.default,
    InviteUserToChannel: invite_user_to_channel_js_1.default,
    RemoveUserFromUsergroup: remove_user_from_usergroup_js_1.default,
    RenameChannel: rename_channel_js_1.default,
    SendDm: send_dm_js_1.default,
    SendEphemeralMessage: send_ephemeral_message_js_1.default,
    SendMessage: send_message_js_1.default,
    UpdateChannelTopic: update_channel_topic_js_1.default,
};
exports.default = SlackFunctions;
