"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const mod_js_1 = require("../../../functions/mod.js");
const schema_types_js_1 = __importDefault(require("../../schema_types.js"));
const schema_types_js_2 = __importDefault(require("../schema_types.js"));
exports.default = (0, mod_js_1.DefineFunction)({
    callback_id: "slack#/functions/remove_user_from_usergroup",
    source_file: "",
    title: "Remove user from user group",
    description: "Remove someone from a Slack user group.",
    input_parameters: {
        required: ["usergroup_id", "user_ids"],
        properties: {
            usergroup_id: {
                type: schema_types_js_2.default.usergroup_id,
                description: "User group",
            },
            user_ids: {
                type: schema_types_js_1.default.array,
                description: "Users to be removed from user group",
                items: {
                    type: "slack#/types/user_id",
                },
            },
        },
    },
    output_parameters: {
        required: [],
        properties: {
            usergroup_id: {
                type: schema_types_js_2.default.usergroup_id,
                description: "Updated usergroup",
            },
        },
    },
});
