"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const mod_js_1 = require("../../../functions/mod.js");
const schema_types_js_1 = __importDefault(require("../../schema_types.js"));
const schema_types_js_2 = __importDefault(require("../schema_types.js"));
exports.default = (0, mod_js_1.DefineFunction)({
    callback_id: "slack#/functions/rename_channel",
    source_file: "",
    title: "Rename a Channel",
    description: "Rename an existing Slack channel",
    input_parameters: {
        required: ["channel_id", "channel_name"],
        properties: {
            channel_id: {
                type: schema_types_js_2.default.channel_id,
                description: "Channel to rename",
            },
            channel_name: {
                type: schema_types_js_1.default.string,
                description: "New channel name",
            },
        },
    },
    output_parameters: {
        required: ["channel_id"],
        properties: {
            channel_id: {
                type: schema_types_js_2.default.channel_id,
                description: "Renamed Channel",
            },
        },
    },
});
