"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const mod_js_1 = require("../../../functions/mod.js");
const schema_types_js_1 = __importDefault(require("../../schema_types.js"));
const schema_types_js_2 = __importDefault(require("../schema_types.js"));
exports.default = (0, mod_js_1.DefineFunction)({
    callback_id: "slack#/functions/send_ephemeral_message",
    source_file: "",
    title: "Send an Ephemeral message",
    description: "Ephemeral messages are only visible to the assigned user in a channel or DM. Message delivery is not guaranteed - the user must be currently active in Slack. These messages are useful as confirmations after a user has clicked a button or submitted a form.",
    input_parameters: {
        required: ["user_id", "channel_id", "message"],
        properties: {
            user_id: {
                type: schema_types_js_2.default.user_id,
                description: "Send this message to this person",
            },
            channel_id: {
                type: schema_types_js_2.default.channel_id,
                description: "Send this message in this channel",
            },
            message: {
                type: schema_types_js_2.default.blocks,
                description: "Message text",
            },
            thread_ts: {
                type: schema_types_js_1.default.string,
                description: "Another Message's ts value to make this message a reply",
            },
        },
    },
    output_parameters: {
        required: ["ts"],
        properties: {
            ts: {
                type: schema_types_js_1.default.string,
                description: "Timestamp of the message that was sent",
            },
        },
    },
});
