"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/** This file was autogenerated on Wed Jul 06 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
const mod_js_1 = require("../../../functions/mod.js");
const schema_types_js_1 = __importDefault(require("../../schema_types.js"));
const schema_types_js_2 = __importDefault(require("../schema_types.js"));
exports.default = (0, mod_js_1.DefineFunction)({
    callback_id: "slack#/functions/send_dm",
    source_file: "",
    title: "Send a direct message (experimental)",
    description: "Sends a direct message to a user.",
    input_parameters: {
        required: ["user_id", "message"],
        properties: {
            user_id: {
                type: schema_types_js_2.default.user_id,
                description: "Send this message to this user",
            },
            message: {
                type: schema_types_js_2.default.blocks,
                description: "Message Text",
            },
            thread_ts: {
                type: schema_types_js_1.default.string,
                description: "Another Message's ts value to make this message a reply",
            },
        },
    },
    output_parameters: {
        required: ["ts"],
        properties: {
            ts: {
                type: schema_types_js_1.default.string,
                description: "Timestamp of the message that was sent",
            },
        },
    },
});
