import {
  autogeneratedComment,
  getFunctionName,
  renderFunctionImport,
} from "./template_utils.ts";
import { FunctionRecord } from "./types.ts";

const renderFunctionPropWithType = (fn: FunctionRecord) => {
  return `${getFunctionName(fn.callback_id)}: ${
    getFunctionName(fn.callback_id)
  }`;
};

export const SlackFunctionModTemplate = (slackFunctions: FunctionRecord[]) => {
  const callbackIds = slackFunctions.map((fn) => fn.callback_id);
  const typescript: string[] = [];
  typescript.push(autogeneratedComment());
  callbackIds.forEach((callbackId) => {
    typescript.push(renderFunctionImport(callbackId));
  });

  typescript.push("");
  typescript.push(
    `const SlackFunctions = {${
      slackFunctions.map((fn) => renderFunctionPropWithType(fn)).join(",")
    }} as const;`,
  );
  typescript.push("");
  typescript.push(`export default SlackFunctions;`);

  return typescript.join("\n");
};

export default SlackFunctionModTemplate;
