// export { assertEquals } from "https://deno.land/std@0.152.0/testing/asserts.ts";
// import SchemaTypes from "../../../../../schema_types.ts";
// import SlackSchemaTypes from "../../../../schema_types.ts";
// import { InternalSlackTypes } from "../../../../types/custom/mod.ts";
// import {
//   autogeneratedComment,
//   getDefineFunctionInput,
//   getFunctionName,
//   getManifestFunctionSchema,
//   renderFunctionImport,
// } from "../template_utils.ts";
// import {
//   ManifestFunctionSchema,
// } from "../../../../../../manifest/manifest_schema.ts";
// import { DefineFunctionInput, FunctionRecord } from "../types.ts";
// import {
//   assertEquals,
//   assertStringIncludes,
// } from "https://deno.land/std@0.152.0/testing/asserts.ts";

// const DESCRIPTION = "Test the built-in function template";
// const TITLE = "test function";
// const CALLBACK_ID = "test_function";
// const SOURCE_FILE = "";

// Deno.test("getDefineFunctionInput should return proper callback_id", () => {
//   const actual: DefineFunctionInput = {
//     callback_id: `slack#/functions/${CALLBACK_ID}`,
//     description: DESCRIPTION,
//     input_parameters: {
//       properties: {},
//       required: [],
//     },
//     output_parameters: {
//       properties: {},
//       required: [],
//     },
//     source_file: SOURCE_FILE,
//     title: TITLE,
//   };
//   const functionRecord: FunctionRecord = {
//     callback_id: CALLBACK_ID,
//     title: TITLE,
//     description: DESCRIPTION,
//     type: "builtin",
//     input_parameters: [],
//     output_parameters: [],
//   };
//   const expected = getDefineFunctionInput(functionRecord);

//   assertEquals(actual, expected);
// });
