import { pascalCase } from "https://deno.land/x/case@v2.1.0/mod.ts";
import { DefineFunctionInput } from "../types.ts";

export function autogeneratedComment(): string {
  const time = new Date();
  return `/** This file was autogenerated on ${time.toDateString()}. Follow the steps in src/schema/slack/functions/README.md to rebuild **/`;
}

export function renderFunctionImport(callbackId: string): string {
  return `import ${getFunctionName(callbackId)} from "./${callbackId}.ts";`;
}

export function getFunctionName(callbackId: string): string {
  return pascalCase(callbackId);
}

export function getSlackCallbackId(
  defineFunctionInput: DefineFunctionInput,
): string {
  return `slack#/functions/${defineFunctionInput.callbackId}`;
}
