import {
  autogeneratedComment,
  getFunctionName,
  renderFunctionDocstring,
  renderFunctionImport,
} from "./template_utils.ts";
import { FunctionRecord } from "../types.ts";

export const SlackFunctionModTemplate = (
  functionRecords: FunctionRecord[],
) => {
  const callbackIds = functionRecords.map((dfi) => dfi.callback_id);
  const typescript: string[] = [];
  typescript.push(autogeneratedComment());
  callbackIds.forEach((callbackId) => {
    typescript.push(renderFunctionImport(callbackId));
  });

  typescript.push("");
  typescript.push(
    `const SlackFunctions = {${
      functionRecords.map((dfi) => {
        const docstring = renderFunctionDocstring(dfi.callback_id);
        const functionName = getFunctionName(dfi.callback_id);
        return `\n${docstring}\n${functionName}`;
      }).join(",")
    }} as const;`,
  );
  typescript.push("");
  typescript.push(`export default SlackFunctions;`);

  return typescript.join("\n");
};

export default SlackFunctionModTemplate;
