import {
  autogeneratedComment,
  getFunctionName,
  renderFunctionImport,
} from "./template_utils.ts";
import { FunctionRecord } from "../types.ts";

const renderFunctionPropWithType = (defineFunctionInput: FunctionRecord) =>
  `${getFunctionName(defineFunctionInput.callback_id)}: ${
    getFunctionName(defineFunctionInput.callback_id)
  }`;

export const SlackFunctionModTemplate = (
  defineFunctionInputs: FunctionRecord[],
) => {
  const callbackIds = defineFunctionInputs.map((dfi) => dfi.callback_id);
  const typescript: string[] = [];
  typescript.push(autogeneratedComment());
  callbackIds.forEach((callbackId) => {
    typescript.push(renderFunctionImport(callbackId));
  });

  typescript.push("");
  typescript.push(
    `const SlackFunctions = {${
      defineFunctionInputs.map((dfi) => renderFunctionPropWithType(dfi)).join(
        ",",
      )
    }} as const;`,
  );
  typescript.push("");
  typescript.push(`export default SlackFunctions;`);

  return typescript.join("\n");
};

export default SlackFunctionModTemplate;
