/** This file was autogenerated on Tue Feb 07 2023. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/add_bookmark",
  source_file: "",
  title: "Add bookmark to channel",
  description: "Add a bookmark to a channel",
  input_parameters: {
    properties: {
      channel_id: {
        type: SlackTypes.channel_id,
        description: "Search all channels",
      },
      name: {
        type: SchemaTypes.string,
        description: "Enter the bookmark name",
      },
      link: { type: SchemaTypes.string, description: "https://docs.acme.com" },
    },
    required: ["channel_id", "name", "link"],
  },
  output_parameters: {
    properties: {
      channel_id: { type: SlackTypes.channel_id, description: "Channel" },
      bookmark_name: { type: SchemaTypes.string, description: "Bookmark name" },
      bookmark_link: { type: SchemaTypes.string, description: "Bookmark link" },
    },
    required: ["channel_id", "bookmark_name", "bookmark_link"],
  },
});
