// /** This is an autogenerated file. Run ./.slack/sdk/schema/slack/functions/_scripts/generate to rebuild **/
// import { DefineFunction } from "../../../functions/mod.ts";
// import SlackTypes from "../schema_types.ts";

// export default DefineFunction(
//   {
//     callback_id: "slack#/functions/add_user_to_usergroup",
//     source_file: "",
//     title: "Add to user group",
//     description: "Add someone to a Slack user group.",
//     input_parameters: {
//       required: ["usergroup_id", "user_id"],
//       properties: {
//         usergroup_id: {
//           type: SlackTypes.usergroup_id,
//           description: "User group",
//         },
//         user_id: {
//           type: SlackTypes.user_id,
//           description: "Person to add to the user group",
//         },
//       },
//     },
//     output_parameters: {
//       required: ["usergroup_id"],
//       properties: {
//         usergroup_id: {
//           type: SlackTypes.usergroup_id,
//           description: "Updated usergroup",
//         },
//       },
//     },
//   },
// );
