/** This is an autogenerated file. Run ./.slack/sdk/schema/slack/functions/_scripts/generate to rebuild **/
import { DefineFunctionStatic } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunctionStatic(
  "slack#/functions/add_pin",
  {
    title: "Pin to channel",
    description: "Pin a message to a channel.",
    input_parameters: {
      required: ["channel_id", "message"],
      properties: {
        channel_id: {
          type: SlackTypes.channel_id,
          description: "Pin message to this channel",
        },
        message: {
          type: SchemaTypes.string,
          description: "Message URL or timestamp",
        },
      },
    },
    output_parameters: {
      required: [],
      properties: {},
    },
  },
);
