/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/add_canvas_to_channel_tab",
  source_file: "",
  title: "Add a canvas to channel tab",
  input_parameters: {
    properties: {
      label: {
        type: SchemaTypes.string,
        description: "Enter a tab label",
        title: "Tab label",
      },
      channel_id: {
        type: SlackTypes.channel_id,
        description: "Channel name",
        title: "Select a channel",
      },
      canvas_id: {
        type: SlackTypes.canvas_id,
        description: "Search all canvases",
        title: "Select a canvas to add as a tab",
      },
    },
    required: ["channel_id", "canvas_id"],
  },
  output_parameters: {
    properties: {
      canvas_id: {
        type: SlackTypes.canvas_id,
        description: "Canvas link",
        title: "Canvas link",
      },
      channel_id: {
        type: SlackTypes.channel_id,
        description: "Channel name",
        title: "Channel name",
      },
    },
    required: ["canvas_id", "channel_id"],
  },
});
