/** This file was autogenerated on Mon Feb 06 2023. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../workflows/mod.ts";
import { ManifestFunctionSchema } from "../../../manifest/manifest_schema.ts";
import SlackTypes from "../schema_types.ts";
import AddUserToUsergroup from "./add_user_to_usergroup.ts";

Deno.test("AddUserToUsergroup generates valid FunctionManifest", () => {
  assertEquals(
    AddUserToUsergroup.definition.callback_id,
    "slack#/functions/add_user_to_usergroup",
  );
  const expected: ManifestFunctionSchema = {
    source_file: "",
    title: "Add to user group",
    description: "Add someone to a user group.",
    input_parameters: {
      properties: {
        usergroup_id: {
          type: SlackTypes.usergroup_id,
          description: "Search all user groups",
        },
        user_id: { type: SlackTypes.user_id, description: "Search all people" },
      },
      required: ["usergroup_id", "user_id"],
    },
    output_parameters: {
      properties: {
        usergroup_id: {
          type: SlackTypes.usergroup_id,
          description: "User group",
        },
      },
      required: ["usergroup_id"],
    },
  };
  const actual = AddUserToUsergroup.export();

  assertEquals(actual, expected);
});

Deno.test("AddUserToUsergroup can be used as a built-in function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddUserToUsergroup_built_in",
    title: "Test AddUserToUsergroup",
    description: "This is a generated test to test AddUserToUsergroup",
  });
  testWorkflow.addStep(AddUserToUsergroup, {
    usergroup_id: "test",
    user_id: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "slack#/functions/add_user_to_usergroup");
  assertEquals(actual.inputs, { usergroup_id: "test", user_id: "test" });
});
