/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { assertEquals, assertNotStrictEquals } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../workflows/mod.ts";
import type { ManifestFunctionSchema } from "../../../manifest/manifest_schema.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";
import AddReaction from "./add_reaction.ts";

Deno.test("AddReaction generates valid FunctionManifest", () => {
  assertEquals(
    AddReaction.definition.callback_id,
    "slack#/functions/add_reaction",
  );
  const expected: ManifestFunctionSchema = {
    source_file: "",
    title: "Add a reaction to a message",
    input_parameters: {
      properties: {
        message_context: {
          type: SlackTypes.message_context,
          description: "Select a message to react to",
          title: "Select a message to react to",
        },
        emoji: {
          type: SchemaTypes.string,
          description: "Reaction (emoji) name",
          title: "Emoji",
        },
      },
      required: ["message_context", "emoji"],
    },
    output_parameters: { properties: {}, required: [] },
  };
  const actual = AddReaction.export();

  assertNotStrictEquals(actual, expected);
});

Deno.test("AddReaction can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddReaction_slack_function",
    title: "Test AddReaction",
    description: "This is a generated test to test AddReaction",
  });
  testWorkflow.addStep(AddReaction, { message_context: "test", emoji: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "slack#/functions/add_reaction");
  assertEquals(actual.inputs, { message_context: "test", emoji: "test" });
});
