/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/canvas_fetch_header_sections",
  source_file: "",
  title: "Fetch canvas header sections",
  description: "Fetch allheader sections in a Canvas",
  input_parameters: {
    properties: {
      canvas_id: {
        type: SlackTypes.canvas_id,
        description: "ID of the Canvas",
        title: "Canvas ID",
      },
      channel_id: {
        type: SlackTypes.channel_id,
        description: "ID of the Channel",
        title: "Channel ID",
      },
    },
    required: [],
  },
  output_parameters: {
    properties: {
      sections: {
        type: SchemaTypes.array,
        description: "Sections",
        title: "Sections",
        items: { type: SchemaTypes.object },
      },
    },
    required: [],
  },
});
