/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/canvas_fetch_placeholders",
  source_file: "",
  title: "Fetch canvas placeholders",
  description: "Fetch all placeholders in a Canvas",
  input_parameters: {
    properties: {
      canvas_id: {
        type: SlackTypes.canvas_id,
        description: "ID of the Canvas template",
        title: "Canvas template ID",
      },
    },
    required: ["canvas_id"],
  },
  output_parameters: {
    properties: {
      placeholders: {
        type: SchemaTypes.array,
        description: "Placeholders",
        title: "Placeholders",
        items: { type: SchemaTypes.object },
      },
    },
    required: ["placeholders"],
  },
});
