/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import {
  assertEquals,
  assertExists,
  assertNotStrictEquals,
} from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../workflows/mod.ts";
import { ManifestFunctionSchema } from "../../../manifest/manifest_schema.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";
import { SlackPrimitiveTypes } from "../../slack/types/mod.ts";

import CanvasCopy from "./canvas_copy.ts";

Deno.test("CanvasCopy generates valid FunctionManifest", () => {
  assertEquals(
    CanvasCopy.definition.callback_id,
    "slack#/functions/canvas_copy",
  );
  const expected: ManifestFunctionSchema = {
    source_file: "",
    title: "Copy a canvas",
    input_parameters: {
      properties: {
        canvas_id: {
          type: SlackPrimitiveTypes.canvas_id,
          description: "Search all canvases",
          title: "Select a canvas",
        },
        title: {
          type: SchemaTypes.string,
          description: "Enter a canvas name",
          title: "Canvas name",
        },
        owner_id: {
          type: SlackTypes.user_id,
          description: "Canvas owner id",
          title: "Owner",
        },
        placeholder_values: {
          type: SchemaTypes.object,
          description: "Variables",
          title: "Variables",
        },
      },
      required: ["canvas_id", "title", "owner_id"],
    },
    output_parameters: {
      properties: {
        canvas_id: {
          type: SlackPrimitiveTypes.canvas_id,
          description: "Canvas link",
          title: "Canvas link",
        },
      },
      required: ["canvas_id"],
    },
  };
  const actual = CanvasCopy.export();

  assertNotStrictEquals(actual, expected);
});

Deno.test("CanvasCopy can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CanvasCopy_slack_function",
    title: "Test CanvasCopy",
    description: "This is a generated test to test CanvasCopy",
  });
  testWorkflow.addStep(CanvasCopy, {
    canvas_id: "test",
    title: "test",
    owner_id: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "slack#/functions/canvas_copy");
  assertEquals(actual.inputs, {
    canvas_id: "test",
    title: "test",
    owner_id: "test",
  });
});

Deno.test("All outputs of Slack function CanvasCopy should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CanvasCopy_slack_function",
    title: "Test CanvasCopy",
    description: "This is a generated test to test CanvasCopy",
  });
  const step = testWorkflow.addStep(CanvasCopy, {
    canvas_id: "test",
    title: "test",
    owner_id: "test",
  });
  assertExists(step.outputs.canvas_id);
});
