/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import {
  assertEquals,
  assertExists,
  assertNotStrictEquals,
} from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../workflows/mod.ts";
import { ManifestFunctionSchema } from "../../../manifest/manifest_schema.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";
import CanvasFetchHeaderSections from "./canvas_fetch_header_sections.ts";

Deno.test("CanvasFetchHeaderSections generates valid FunctionManifest", () => {
  assertEquals(
    CanvasFetchHeaderSections.definition.callback_id,
    "slack#/functions/canvas_fetch_header_sections",
  );
  const expected: ManifestFunctionSchema = {
    source_file: "",
    title: "Fetch canvas header sections",
    description: "Fetch allheader sections in a Canvas",
    input_parameters: {
      properties: {
        canvas_id: {
          type: SlackTypes.canvas_id,
          description: "ID of the Canvas",
          title: "Canvas ID",
        },
        channel_id: {
          type: SlackTypes.channel_id,
          description: "ID of the Channel",
          title: "Channel ID",
        },
      },
      required: [],
    },
    output_parameters: {
      properties: {
        sections: {
          type: SchemaTypes.array,
          description: "Sections",
          title: "Sections",
          items: { type: SchemaTypes.object },
        },
      },
      required: [],
    },
  };
  const actual = CanvasFetchHeaderSections.export();

  assertNotStrictEquals(actual, expected);
});

Deno.test("CanvasFetchHeaderSections can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CanvasFetchHeaderSections_slack_function",
    title: "Test CanvasFetchHeaderSections",
    description: "This is a generated test to test CanvasFetchHeaderSections",
  });
  testWorkflow.addStep(CanvasFetchHeaderSections, {});
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "slack#/functions/canvas_fetch_header_sections",
  );
  assertEquals(actual.inputs, {});
});

Deno.test("All outputs of Slack function CanvasFetchHeaderSections should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CanvasFetchHeaderSections_slack_function",
    title: "Test CanvasFetchHeaderSections",
    description: "This is a generated test to test CanvasFetchHeaderSections",
  });
  const step = testWorkflow.addStep(CanvasFetchHeaderSections, {});
  assertExists(step.outputs.sections);
});
