/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/copy_list",
  source_file: "",
  title: "Copy a list",
  input_parameters: {
    properties: {
      list_id: {
        type: undefined,
        description: "Search all lists",
        title: "Select a list",
      },
      owner_id: {
        type: SlackTypes.user_id,
        description: "List owner id",
        title: "Owner",
      },
      name: {
        type: SchemaTypes.string,
        description: "Name of the list",
        title: "Name",
      },
      description: {
        type: SchemaTypes.string,
        description: "Description of the list",
        title: "Description",
      },
      emoji: {
        type: SchemaTypes.string,
        description: "Emoji for the list",
        title: "Emoji",
      },
      include_copied_list_records: {
        type: SchemaTypes.boolean,
        description: "Include records from the copied list",
        title: "Copy records",
      },
    },
    required: ["list_id", "owner_id", "name", "include_copied_list_records"],
  },
  output_parameters: {
    properties: {
      list_id: {
        type: SchemaTypes.string,
        description: "List ID",
        title: "List ID",
      },
      link: {
        type: SchemaTypes.string,
        description: "Link for the list",
        title: "Link",
      },
      list_id_value: {
        type: undefined,
        description: "List title",
        title: "List title",
      },
    },
    required: [],
  },
});
