/** This is an autogenerated file. Run ./.slack/sdk/schema/slack/functions/_scripts/generate to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction(
  {
    callback_id: "slack#/functions/create_channel",
    source_file: "",
    title: "Create Channel",
    description: "Creates a new channel",
    input_parameters: {
      required: ["channel_name"],
      properties: {
        channel_name: {
          type: SchemaTypes.string,
          description: "Channel Name",
        },
        is_private: {
          type: SchemaTypes.boolean,
          description: "Make Private",
        },
      },
    },
    output_parameters: {
      required: ["channel_id"],
      properties: {
        channel_id: {
          type: SlackTypes.channel_id,
          description: "Created Channel",
        },
      },
    },
  },
);
