/** This is an autogenerated file. Run ./.slack/sdk/schema/slack/functions/_scripts/generate to rebuild **/
import { DefineFunctionStatic } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";

export default DefineFunctionStatic(
  "slack#/functions/delay",
  {
    title: "Delay",
    description: "Pause your workflow by adding a delay!",
    input_parameters: {
      required: ["minutes_to_delay"],
      properties: {
        minutes_to_delay: {
          type: SchemaTypes.integer,
          description: "Minutes to Delay",
        },
      },
    },
    output_parameters: {
      required: [],
      properties: {},
    },
  },
);
