/** This file was autogenerated on Mon Aug 01 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";

export default DefineFunction(
  {
    callback_id: "slack#/functions/delay",
    source_file: "",
    title: "Delay",
    description: "Pause your workflow by adding a delay!",
    input_parameters: {
      required: ["minutes_to_delay"],
      properties: {
        minutes_to_delay: {
          type: SchemaTypes.integer,
          description: "Minutes to Delay",
        },
      },
    },
    output_parameters: {
      required: [],
      properties: {},
    },
  },
);
