/** This file was autogenerated on Tue Feb 14 2023. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction(
  {
    callback_id: "slack#/functions/invite_user_to_channel",
    source_file: "",
    title: "Invite to channel",
    description:
      "Invite someone to a channel. This will only work if this workflow created the channel.",
    input_parameters: {
      required: [],
      properties: {
        channel_id: {
          type: SlackTypes.channel_id,
          description: "Search all channels",
        },
        user_id: {
          type: SlackTypes.user_id,
          description: "Search all people",
        },
        channel_ids: {
          type: SchemaTypes.array,
          description: "Search all channels",
          items: {
            type: "slack#/types/channel_id",
          },
        },
        user_ids: {
          type: SchemaTypes.array,
          description: "Search all people",
          items: {
            type: "slack#/types/user_id",
          },
        },
      },
    },
    output_parameters: {
      required: [],
      properties: {
        user_id: {
          type: SlackTypes.user_id,
          description: "Person who was invited",
        },
        user_ids: {
          type: SchemaTypes.array,
          description: "Person(s) who were invited",
          items: {
            type: "slack#/types/user_id",
          },
        },
      },
    },
  },
);
