/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { assertEquals, assertNotStrictEquals } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../workflows/mod.ts";
import { ManifestFunctionSchema } from "../../../manifest/manifest_schema.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";
import ListsActivityFeed from "./lists_activity_feed.ts";

Deno.test("ListsActivityFeed generates valid FunctionManifest", () => {
  assertEquals(
    ListsActivityFeed.definition.callback_id,
    "slack#/functions/lists_activity_feed",
  );
  const expected: ManifestFunctionSchema = {
    source_file: "",
    title: "Send notification to activity feed",
    input_parameters: {
      properties: {
        user_id: {
          type: SlackTypes.user_id,
          description: "Select a user",
          title: "Select a user",
        },
        updated_by_user_id: {
          type: SlackTypes.user_id,
          description: "User who updated the list item",
          title: "User who updated the list item",
        },
        list_id: {
          type: undefined,
          description: "Select a list",
          title: "Select a list",
        },
        record_id: {
          type: SchemaTypes.string,
          description: "Item ID",
          title: "Item ID",
        },
        columns: {
          type: SchemaTypes.string,
          description: "Field IDs",
          title: "Field IDs",
        },
      },
      required: ["user_id", "list_id", "record_id", "columns"],
    },
    output_parameters: { properties: {}, required: [] },
  };
  const actual = ListsActivityFeed.export();

  assertNotStrictEquals(actual, expected);
});

Deno.test("ListsActivityFeed can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_ListsActivityFeed_slack_function",
    title: "Test ListsActivityFeed",
    description: "This is a generated test to test ListsActivityFeed",
  });
  testWorkflow.addStep(ListsActivityFeed, {
    user_id: "test",
    list_id: "test",
    record_id: "test",
    columns: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "slack#/functions/lists_activity_feed");
  assertEquals(actual.inputs, {
    user_id: "test",
    list_id: "test",
    record_id: "test",
    columns: "test",
  });
});
