/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/list_add_record",
  source_file: "",
  title: "Add an item to a list",
  description: "Add an item to a given list",
  input_parameters: {
    properties: {
      list_id: {
        type: SlackTypes.list_id,
        description: "Search all lists",
        title: "Select a list",
      },
      columns: {
        type: SchemaTypes.object,
        description: "Enter the data for each field",
        title: "Fields",
      },
    },
    required: ["list_id", "columns"],
  },
  output_parameters: {
    properties: {
      record_id: {
        type: SchemaTypes.string,
        description: "The item ID of the new item",
        title: "Item ID",
      },
      record_url: {
        type: SchemaTypes.string,
        description: "The URL of the new item",
        title: "Item URL",
      },
    },
    required: ["record_id", "record_url"],
  },
});
