/** This file was autogenerated on Tue Feb 14 2023. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction(
  {
    callback_id: "slack#/functions/remove_user_from_usergroup",
    source_file: "",
    title: "Remove from a user group",
    description: "Remove someone from a user group",
    input_parameters: {
      required: ["usergroup_id"],
      properties: {
        usergroup_id: {
          type: SlackTypes.usergroup_id,
          description: "Search all user groups",
        },
        user_id: {
          type: SlackTypes.user_id,
          description: "Search all people",
        },
        user_ids: {
          type: SchemaTypes.array,
          description: "Search all people",
          items: {
            type: "slack#/types/user_id",
          },
        },
      },
    },
    output_parameters: {
      required: [],
      properties: {
        usergroup_id: {
          type: SlackTypes.usergroup_id,
          description: "User group",
        },
      },
    },
  },
);
