/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/remove_reaction",
  source_file: "",
  title: "Remove a reaction from a message",
  input_parameters: {
    properties: {
      message_context: {
        type: SlackTypes.message_context,
        description: "Select a message to unreact from",
        title: "Select a message to unreact from",
      },
      emoji: {
        type: SchemaTypes.string,
        description: "Reaction (emoji) name",
        title: "Emoji",
      },
    },
    required: ["message_context", "emoji"],
  },
  output_parameters: { properties: {}, required: [] },
});
