/** This is an autogenerated file. Run ./.slack/sdk/schema/slack/functions/_scripts/generate to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction(
  {
    callback_id: "slack#/functions/send_message",
    source_file: "",
    title: "Send a message (experimental)",
    description: "Sends a message to a channel.",
    input_parameters: {
      required: ["channel_id", "message"],
      properties: {
        channel_id: {
          type: SlackTypes.channel_id,
          description: "Send this message to",
        },
        message: {
          type: SchemaTypes.string,
          description: "Message Text",
        },
        thread_ts: {
          type: SchemaTypes.string,
          description:
            "Another Message's ts value to make this message a reply",
        },
        // metadata: {
        //   type: SchemaTypes.object,
        //   description: "The message metadata",
        //   required: ["event_type", "event_payload"],
        //   additionalProperties: true,
        //   properties: {
        //     event_type: {
        //       type: SchemaTypes.string,
        //     },
        //     event_payload: {
        //       type: SchemaTypes.object,
        //     },
        //   },
        // },
      },
    },
    output_parameters: {
      required: ["ts"],
      properties: {
        ts: {
          type: SchemaTypes.string,
          description: "Timestamp of the message that was sent",
        },
      },
    },
  },
);
