/** This file was autogenerated on Wed Aug 03 2022. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction(
  {
    callback_id: "slack#/functions/send_dm",
    source_file: "",
    title: "Send a direct message",
    description: "Send a direct message to someone",
    input_parameters: {
      required: ["user_id", "message"],
      properties: {
        user_id: {
          type: SlackTypes.user_id,
          description: "Search all people",
        },
        message: {
          type: SlackTypes.blocks,
          description: "Add a message",
        },
        thread_ts: {
          type: SchemaTypes.string,
          description:
            "Provide another message's timestamp value to make this message a reply",
        },
      },
    },
    output_parameters: {
      required: ["message_ts", "message_link"],
      properties: {
        message_ts: {
          type: SchemaTypes.string,
          description: "Timestamp of the message sent",
        },
        message_link: {
          type: SchemaTypes.string,
          description: "Permalink URL of the message sent",
        },
      },
    },
  },
);
