/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/send_dm",
  source_file: "",
  title: "Send a message to a person",
  input_parameters: {
    properties: {
      user_id: {
        type: SlackTypes.user_id,
        description: "Search all people",
        title: "Select a member",
      },
      message: {
        type: SlackTypes.rich_text,
        description: "Add a message",
        title: "Add a message",
      },
      interactive_blocks: {
        type: SlackTypes.blocks,
        description: "Button(s) to send with the message",
        title: "Button(s) to send with the message",
      },
    },
    required: ["user_id", "message"],
  },
  output_parameters: {
    properties: {
      message_timestamp: {
        type: SlackTypes.timestamp,
        description: "Message timestamp",
        title: "Message timestamp",
      },
      message_link: {
        type: SchemaTypes.string,
        description: "Message link",
        title: "Message link",
      },
      message_context: {
        type: SlackTypes.message_context,
        description: "Reference to the message sent",
        title: "Reference to the message sent",
      },
    },
    required: [
      "message_timestamp",
      "message_link",
      "message_context",
      "timestamp_started",
      "timestamp_completed",
    ],
  },
});
