/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/share_canvas_in_thread",
  source_file: "",
  title: "Share canvas in thread",
  input_parameters: {
    properties: {
      canvas_id: {
        type: SlackTypes.canvas_id,
        description: "Search all canvases",
        title: "Select a canvas",
      },
      message_context: {
        type: SlackTypes.message_context,
        description: "Select a message to reply to",
        title: "Select a message to reply to",
      },
      access_level: {
        type: SchemaTypes.string,
        description: "Select an option",
        title: "Select access level",
      },
      message: {
        type: SlackTypes.rich_text,
        description: "Add a message",
        title: "Add a message",
      },
      reply_broadcast: {
        type: SchemaTypes.boolean,
        description: "Also send to conversation",
        title: "Also send to conversation",
      },
    },
    required: ["canvas_id", "message_context", "access_level"],
  },
  output_parameters: {
    properties: {
      canvas_id: {
        type: SlackTypes.canvas_id,
        description: "Canvas link",
        title: "Canvas link",
      },
      message_context: {
        type: SlackTypes.message_context,
        description: "Reference to the message sent",
        title: "Reference to the message sent",
      },
    },
    required: [],
  },
});
