/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";
import { SlackPrimitiveTypes } from "../../slack/types/mod.ts";

export default DefineFunction({
  callback_id: "slack#/functions/share_canvas",
  source_file: "",
  title: "Share a canvas",
  input_parameters: {
    properties: {
      canvas_id: {
        type: SlackPrimitiveTypes.canvas_id,
        description: "Search all canvases",
        title: "Select a canvas",
      },
      channel_ids: {
        type: SchemaTypes.array,
        description: "Select channels",
        title: "Select channels",
        items: { type: SlackTypes.channel_id },
      },
      user_ids: {
        type: SchemaTypes.array,
        description: "Search users",
        title: "Select people",
        items: { type: SlackTypes.user_id },
      },
      access_level: {
        type: SchemaTypes.string,
        description: "Select an option",
        title: "Select access level",
      },
      message: {
        type: SlackTypes.rich_text,
        description: "Add a message",
        title: "Add a message",
      },
    },
    required: ["canvas_id", "access_level"],
  },
  output_parameters: {
    properties: {
      canvas_id: {
        type: SlackPrimitiveTypes.canvas_id,
        description: "Canvas link",
        title: "Canvas link",
      },
    },
    required: [],
  },
});
