/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction({
  callback_id: "slack#/functions/update_list_record",
  source_file: "",
  title: "Update a list item",
  input_parameters: {
    properties: {
      list_id: {
        type: SlackTypes.list_id,
        description: "Select a list",
        title: "Select a list",
      },
      record_id: {
        type: SchemaTypes.string,
        description: "Item ID",
        title: "Item ID",
      },
      updated_columns: {
        type: SchemaTypes.object,
        description: "Enter the data for fields",
        title: "Updated fields",
      },
    },
    required: ["list_id", "updated_columns"],
  },
  output_parameters: {
    properties: {
      field_values: {
        type: SchemaTypes.object,
        description: "Updated values of the item",
        title: "Item",
      },
    },
    required: [],
  },
});
