/** This file was autogenerated. Follow the steps in src/schema/slack/functions/_scripts/README.md to rebuild **/
import {
  assertEquals,
  assertExists,
  assertNotStrictEquals,
} from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../workflows/mod.ts";
import { ManifestFunctionSchema } from "../../../manifest/manifest_schema.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";
import UpdateListRecord from "./update_list_record.ts";

Deno.test("UpdateListRecord generates valid FunctionManifest", () => {
  assertEquals(
    UpdateListRecord.definition.callback_id,
    "slack#/functions/update_list_record",
  );
  const expected: ManifestFunctionSchema = {
    source_file: "",
    title: "Update a list item",
    input_parameters: {
      properties: {
        list_id: {
          type: SlackTypes.list_id,
          description: "Select a list",
          title: "Select a list",
        },
        record_id: {
          type: SchemaTypes.string,
          description: "Item ID",
          title: "Item ID",
        },
        updated_columns: {
          type: SchemaTypes.object,
          description: "Enter the data for fields",
          title: "Updated fields",
        },
      },
      required: ["list_id", "updated_columns"],
    },
    output_parameters: {
      properties: {
        field_values: {
          type: SchemaTypes.object,
          description: "Updated values of the item",
          title: "Item",
        },
      },
      required: [],
    },
  };
  const actual = UpdateListRecord.export();

  assertNotStrictEquals(actual, expected);
});

Deno.test("UpdateListRecord can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateListRecord_slack_function",
    title: "Test UpdateListRecord",
    description: "This is a generated test to test UpdateListRecord",
  });
  testWorkflow.addStep(UpdateListRecord, {
    list_id: "test",
    updated_columns: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "slack#/functions/update_list_record");
  assertEquals(actual.inputs, { list_id: "test", updated_columns: "test" });
});

Deno.test("All outputs of Slack function UpdateListRecord should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateListRecord_slack_function",
    title: "Test UpdateListRecord",
    description: "This is a generated test to test UpdateListRecord",
  });
  const step = testWorkflow.addStep(UpdateListRecord, {
    list_id: "test",
    updated_columns: "test",
  });
  assertExists(step.outputs.field_values);
});
