/** This is an autogenerated file. Run ./.slack/sdk/schema/slack/functions/_scripts/generate to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import SchemaTypes from "../../schema_types.ts";
import SlackTypes from "../schema_types.ts";

export default DefineFunction(
  {
    callback_id: "slack#/functions/update_channel_topic",
    source_file: "",
    title: "Update channel topic",
    description: "Update a channel topic",
    input_parameters: {
      required: ["channel_id", "topic"],
      properties: {
        channel_id: {
          type: SlackTypes.channel_id,
          description: "Channel",
        },
        topic: {
          type: SchemaTypes.string,
          description: "New topic",
        },
      },
    },
    output_parameters: {
      required: ["topic"],
      properties: {
        topic: {
          type: SchemaTypes.string,
          description: "The string to which the channel topic was updated",
        },
      },
    },
  },
);
