name: Deno

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deno-version:
          - v1.x
          - v2.x
    permissions:
      contents: read
    steps:
      - name: Setup repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@ff4860f9d7236f320afa0f82b7e6457384805d05 # v2.0.4
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Run tests
        run: deno task test

      - name: Generate CodeCov-friendly coverage report
        run: deno task coverage

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: matrix.deno-version == 'v2.x'
        with:
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
