# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build & Deploy to NPM

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Actions checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2.x

      - name: Get the tag name
        id: get_tag_name
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Run build_npm.ts
        run: deno run -A scripts/build_npm.ts "$TAG"
        env:
          TAG: ${{steps.get_tag_name.outputs.TAG}}

      - name: Publish to NPM
        run: cd npm && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
