# This workflow runs a test build for npm against changes on main or PRs

name: Npm Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        deno-version:
          - v1.x
          - v2.x
    permissions:
      contents: read
    steps:
      - name: Actions checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@ff4860f9d7236f320afa0f82b7e6457384805d05 # v2.0.4
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Run build_npm.ts
        run: deno run -A scripts/build_npm.ts
