# This workflow runs a test build for npm against changes on main or PRs

name: Npm Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        deno-version:
          - v1.x
          - v2.x
    permissions:
      contents: read
    steps:
      - name: Actions checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.4
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Run build_npm.ts
        run: deno run -A scripts/build_npm.ts
